export const countries = [
  'ab',
  'af',
  'ak',
  'am',
  'an',
  'ar',
  'ascii',
  'av',
  'ay',
  'az',
  'ba',
  'be',
  'bg',
  'bi',
  'bn',
  'bo',
  'br',
  'bs',
  'ca',
  'ce',
  'ch',
  'co',
  'cs',
  'cu',
  'cv',
  'cy',
  'da',
  'de',
  'dv',
  'dz',
  'el',
  'en',
  'eo',
  'es',
  'et',
  'eu',
  'fa',
  'fi',
  'fo',
  'fr',
  'fy',
  'ga',
  'gd',
  'gl',
  'gn',
  'gv',
  'he',
  'hi',
  'hr',
  'ht',
  'hu',
  'hy',
  'ia',
  'id',
  'ie',
  'io',
  'is',
  'it',
  'iu',
  'ja',
  'jv',
  'ka',
  'kg',
  'kk',
  'kl',
  'kn',
  'ko',
  'ku',
  'kv',
  'kw',
  'ky',
  'la',
  'lg',
  'li',
  'ln',
  'lt',
  'lv',
  'mg',
  'mi',
  'mk',
  'ml',
  'mn',
  'mr',
  'ms',
  'mt',
  'my',
  'na',
  'nb',
  'nl',
  'nn',
  'no',
  'oc',
  'os',
  'pl',
  'ps',
  'pt',
  'qu',
  'ro',
  'ru',
  'sc',
  'se',
  'sg',
  'sh',
  'sk',
  'sl',
  'sm',
  'so',
  'sq',
  'sr',
  'ss',
  'st',
  'su',
  'sv',
  'sw',
  'ta',
  'te',
  'tg',
  'th',
  'tk',
  'tl',
  'tr',
  'tt',
  'ty',
  'ug',
  'uk',
  'ur',
  'uz',
  'vi',
  'vo',
  'wa',
  'wo',
  'yi',
  'yo',
  'za',
  'zh',
  'zu',
] as const

export const aqiText = {
  1: {
    type: 'good',
    level: { ru: 'Отличный', en: 'Good' },
    message: {
      ru: 'Качество воздуха считается удовлетворительным, а загрязнение воздуха практически не представляет опасности.',
      en: 'Air quality is considered satisfactory, and air pollution poses little or no risk.',
    },
  },
  2: {
    type: 'fair',
    level: { ru: 'Хороший', en: 'Fair' },
    message: {
      ru: 'Качество воздуха является приемлемым, однако некоторые загрязняющие вещества могут представлять умеренную угрозу для здоровья очень небольшого числа людей, которые необычайно чувствительны к загрязнению воздуха.',
      en: 'Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution.',
    },
  },
  3: {
    type: 'moderate',
    level: { ru: 'Умеренный', en: 'Moderate' },
    message: {
      ru: 'Члены чувствительных групп могут испытывать последствия для здоровья. Широкая общественность, скорее всего, не пострадает.',
      en: 'Members of sensitive groups may experience health effects. The general public is not likely to be affected.',
    },
  },
  4: {
    type: 'poor',
    level: { ru: 'Плохой', en: 'Poor' },
    message: {
      ru: 'Каждый может начать испытывать последствия для здоровья. Члены чувствительных групп могут испытывать более серьезные последствия для здоровья.',
      en: 'Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects',
    },
  },
  5: {
    type: 'veryPoor',
    level: { ru: 'Очень плохой', en: 'Very poor' },
    message: {
      ru: 'Предупреждения о чрезвычайных ситуациях для здоровья. С большей вероятностью пострадает все население.',
      en: 'Health warnings of emergency conditions. The entire population is more likely to be affected.',
    },
  },
}
